### ISSUE TITLE
TEst 4 Bonus

### ISSUE THREAD

**Issue by iqacevedo** [nfbalbontin/GraciasTotalesMavrakis#44]
Hola llevo mucho rato intentado resolver este error, tengo definida una variable `a = [1,2,3]` y otra `b="[4,5,6]"`, cuando intento sumar estas dos listas `a+b` me sale lo siguiente:

```KeyError: can only concatenate list (not "str") to list```

**Comment by nfbalbontin** [comment]
KeyError: can only concatenate list (not "str") to list
